/*
 * generated by Xtext 2.10.0
 */
package mdsdteam17.cmdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ComponentModelStandaloneSetup extends ComponentModelStandaloneSetupGenerated {

	def static void doSetup() {
		new ComponentModelStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
