/*
 * generated by Xtext 2.10.0
 */
package mdsdteam17.cmdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ComponentModelRuntimeModule extends AbstractComponentModelRuntimeModule {
}
