/*
 * generated by Xtext 2.10.0
 */
package mdsdteam17.cmdsl.ide.contentassist.antlr;

import mdsdteam17.cmdsl.ide.contentassist.antlr.internal.InternalComponentModelParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class ComponentModelTokenSource extends AbstractIndentationTokenSource {

	public ComponentModelTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalComponentModelParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalComponentModelParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalComponentModelParser.RULE_END;
	}

	@Override
	protected boolean shouldEmitPendingEndTokens() {
		return false;
	}
}
