<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mdsdteam17" nsURI="http://www.example.org/mdsdteam17" nsPrefix="mdsdteam17">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="View" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modelcontainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//View" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//RepositoryPackage/Type" containment="true"/>
  </eClassifiers>
  <eSubpackages name="EnvironmentPackage" nsURI="http://www.example.org/mdsdteam17/EnvironmentPackage"
      nsPrefix="EnvironmentPackage">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Environment" eSuperTypes="#//View">
      <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
          eType="#//EnvironmentPackage/Container" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containerLinks" upperBound="-1"
          eType="#//EnvironmentPackage/Link" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Link">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="DistinctContainers"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="DistinctContainers" value="&#xA;&#x9;&#x9;&#x9;containers->asSet()->size() = containers->size()"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containers" lowerBound="2"
          upperBound="-1" eType="#//EnvironmentPackage/Container" eOpposite="#//EnvironmentPackage/Container/links"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Container">
      <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
          eType="#//EnvironmentPackage/Link" eOpposite="#//EnvironmentPackage/Link/containers"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="AllocationPackage" nsURI="http://www.example.org/mdsdteam17/AllocationPackage"
      nsPrefix="AllocationPackage">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Allocation" eSuperTypes="#//View">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="ComponentsAreAllocatedOnLinkedContainers"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="ComponentsAreAllocatedOnLinkedContainers" value="&#xA;&#x9;&#x9;&#x9;compositecomponent.assemblyconnectors->forAll(assConnector | &#xA;&#x9;&#x9;&#x9;&#x9;/* They are both on the same container */&#xA;&#x9;&#x9;&#x9;&#x9;allocationcontexts->select(x | &#xA;&#x9;&#x9;&#x9;&#x9;&#x9;x.topLevelContext = assConnector.provider or x.topLevelContext = assConnector.consumer&#xA;&#x9;&#x9;&#x9;&#x9;).container->asSet()->size() = 1&#xA;&#x9;&#x9;&#x9;&#x9;or&#xA;&#x9;&#x9;&#x9;&#x9;/* They are on different containers which are linked */&#xA;&#x9;&#x9;&#x9;&#x9;allocationcontexts->select(x | &#xA;&#x9;&#x9;&#x9;&#x9;&#x9;x.topLevelContext = assConnector.provider or x.topLevelContext = assConnector.consumer&#xA;&#x9;&#x9;&#x9;&#x9;).container.links->exists(l1, l2 | l1 = l2)&#xA;&#x9;&#x9;&#x9;)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocationcontexts" upperBound="-1"
          eType="#//AllocationPackage/AllocationContext" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="compositecomponent" lowerBound="1"
          eType="#//AssemblyPackage/CompositeComponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AllocationContext">
      <eStructuralFeatures xsi:type="ecore:EReference" name="topLevelContext" lowerBound="1"
          eType="#//AssemblyPackage/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
          eType="#//EnvironmentPackage/Container"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="AssemblyPackage" nsURI="http://www.example.org/mdsdteam17/AssemblyPackage"
      nsPrefix="AssemblyPackage">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EEnum" name="DelegationType">
      <eLiterals name="Provided"/>
      <eLiterals name="Required"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Assembly" eSuperTypes="#//View">
      <eStructuralFeatures xsi:type="ecore:EReference" name="compositecomponents"
          lowerBound="1" eType="#//AssemblyPackage/CompositeComponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DelegationConnector">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="assemblyContextHasInterface"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="assemblyContextHasInterface" value="&#xA;&#x9;&#x9;&#x9;&#x9;if delegationType = Provided then&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;assemblyContext.component.providedInterfaces->includes(interface)&#xA;&#x9;&#x9;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;assemblyContext.component.requiredInterfaces->includes(interface)&#xA;&#x9;&#x9;&#x9;&#x9;endif"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
          eType="#//RepositoryPackage/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="delegationType" eType="#//AssemblyPackage/DelegationType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContext" lowerBound="1"
          eType="#//AssemblyPackage/AssemblyContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyContext">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
          eType="#//RepositoryPackage/Component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyConnector">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="providerHasInterface comsumerHasInterface"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="providerHasInterface" value="&#xA;&#x9;&#x9;&#x9;provider.component.providedInterfaces->includes(interface)"/>
        <details key="comsumerHasInterface" value="&#xA;&#x9;&#x9;&#x9;consumer.component.providedInterfaces->includes(interface)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="provider" lowerBound="1"
          eType="#//AssemblyPackage/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="consumer" lowerBound="1"
          eType="#//AssemblyPackage/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
          eType="#//RepositoryPackage/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent" eSuperTypes="#//RepositoryPackage/Component">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="providedInterfacesAreDelegatedOnce requiredInterfacesAreDelegatedOnce delegationsReferenceDirectElements assemblyConnectorsReferenceDirectElements"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="providedInterfacesAreDelegatedOnce" value="&#xA;&#x9;&#x9;&#x9;providedInterfaces = delegationconnectors->select(delegationType = Provided)->collect(interface)"/>
        <details key="requiredInterfacesAreDelegatedOnce" value="&#xA;&#x9;&#x9;&#x9;requiredInterfaces = delegationconnectors->select(delegationType = Required)->collect(interface)"/>
        <details key="delegationsReferenceDirectElements" value="&#xA;&#x9;&#x9;&#x9;&#x9;elements->includesAll(delegationconnectors->collect(assemblyContext))"/>
        <details key="assemblyConnectorsReferenceDirectElements" value="&#xA;&#x9;&#x9;&#x9;&#x9;elements->includesAll(assemblyconnectors->collect(consumer)->union(assemblyconnectors->collect(provider)))"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyconnectors" upperBound="-1"
          eType="#//AssemblyPackage/AssemblyConnector" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="delegationconnectors"
          upperBound="-1" eType="#//AssemblyPackage/DelegationConnector" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//AssemblyPackage/AssemblyContext" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="ComponentBehaviorPackage" nsURI="http://www.example.org/mdsdteam17/ComponentBehaviorPackage"
      nsPrefix="ComponentBehaviorPackage">
    <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalAction" eSuperTypes="#//ComponentBehaviorPackage/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
          eType="#//RepositoryPackage/Signature"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InternalAction" eSuperTypes="#//ComponentBehaviorPackage/Statement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceDemand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoopStatement" eSuperTypes="#//ComponentBehaviorPackage/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" lowerBound="1"
          eType="#//ComponentBehaviorPackage/BlockStatement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iterations" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlockStatement" eSuperTypes="#//ComponentBehaviorPackage/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
          eType="#//ComponentBehaviorPackage/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BranchStatement" eSuperTypes="#//ComponentBehaviorPackage/Statement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="chance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ifStatements" eType="#//ComponentBehaviorPackage/BlockStatement"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseStatements" eType="#//ComponentBehaviorPackage/BlockStatement"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorDescription">
      <eStructuralFeatures xsi:type="ecore:EReference" name="signature" lowerBound="1"
          eType="#//RepositoryPackage/Signature"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" lowerBound="1"
          eType="#//ComponentBehaviorPackage/BlockStatement" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="RepositoryPackage" nsURI="http://www.example.org/mdsdteam17/RepositoryPackage"
      nsPrefix="RepositoryPackage">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Repository" eSuperTypes="#//View">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
          eType="#//RepositoryPackage/Interface" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="#//RepositoryPackage/Component" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="DistinctSignatureNames"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="DistinctSignatureNames" value="&#xA;&#x9;&#x9;&#x9;signatures->isUnique(x | x.name)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="signatures" upperBound="-1"
          eType="#//RepositoryPackage/Signature" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="DistinctProvidedInterfaces DistinctRequiredInterfaces BehaviorIsProvidedSignature"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="DistinctProvidedInterfaces" value="&#xA;&#x9;&#x9;&#x9;providedInterfaces->asSet()->size() = providedInterfaces->size()"/>
        <details key="DistinctRequiredInterfaces" value="&#xA;&#x9;&#x9;&#x9;requiredInterfaces->asSet()->size() = requiredInterfaces->size()"/>
        <details key="BehaviorIsProvidedSignature" value="&#xA;&#x9;&#x9;&#x9;providedInterfaces->collect(signatures)->includesAll(behaviors->collect(signature))"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviors" upperBound="-1"
          eType="#//ComponentBehaviorPackage/BehaviorDescription" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterfaces" upperBound="-1"
          eType="#//RepositoryPackage/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterfaces" lowerBound="1"
          upperBound="-1" eType="#//RepositoryPackage/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterType" abstract="true" eSuperTypes="#//RepositoryPackage/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleType" eSuperTypes="#//RepositoryPackage/ParameterType"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComplexType" eSuperTypes="#//RepositoryPackage/ParameterType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Signature">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="DistinctParameterNames"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="DistinctParameterNames" value="&#xA;&#x9;&#x9;&#x9;parameters->isUnique(x | x.name)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
          eType="#//RepositoryPackage/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//RepositoryPackage/SignatureParameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SignatureParameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//RepositoryPackage/ParameterType"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
