/*
 * generated by Xtext 2.10.0
 */
package mdsdteam17.cmdsl.parser.antlr;

import mdsdteam17.cmdsl.parser.antlr.internal.InternalComponentModelParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class ComponentModelTokenSource extends AbstractIndentationTokenSource {

	public ComponentModelTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		return token.getType() == InternalComponentModelParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		return InternalComponentModelParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		return InternalComponentModelParser.RULE_END;
	}

}
